sudo: required
dist: trusty
language: ocaml
branches:
  only:
  - 1.0
  - /^deploy-.*$/
services:
- docker
notifications:
  email:
  - tracker@easycrypt.info
before_install:
- docker pull easycryptpa/ec-build-box
script:
- >-
  docker run -v $PWD:/home/ci/easycrypt easycryptpa/ec-build-box
  sh -c 'cd easycrypt && opam config exec -- make'
